name: fake_pipe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  specs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ 2.7, 3.1, 3.2 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run tests
        run: bundle exec rspec --backtrace
